# Generated by Django 2.1.15 on 2020-04-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title of album')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name of artist')),
            ],
            options={
                'verbose_name': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Composer', models.CharField(max_length=220)),
                ('Milliseconds', models.IntegerField()),
                ('Bytes', models.IntegerField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disks.Album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disks.Artist', verbose_name='artist'),
        ),
    ]
