# Generated by Django 2.1.15 on 2020-04-23 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'artiste'},
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disks.Artist', verbose_name='artiste'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=200, verbose_name="titre de l'album"),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=120, verbose_name="nom de l'artiste"),
        ),
        migrations.AlterField(
            model_name='track',
            name='Composer',
            field=models.CharField(max_length=220, verbose_name='compositeur'),
        ),
        migrations.AlterField(
            model_name='track',
            name='Milliseconds',
            field=models.TextField(verbose_name='duree'),
        ),
        migrations.AlterField(
            model_name='track',
            name='Name',
            field=models.CharField(max_length=200, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='track',
            name='UnitPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix unitaire'),
        ),
    ]
