# Generated by Django 2.1.15 on 2020-04-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0002_auto_20200423_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='Name',
        ),
    ]
